#!/usr/bin/env node
/**
 * Production smoke test over HTTP. Start the web app (WORKER_MODE=external) AND `npm run worker` as separate processes first, both with
 * KNOWLEDGE_FETCHER=fixture ALLOW_FIXTURE_DOCS=true (fixtures only; a real deployment uses KNOWLEDGE_FETCHER=http).
 *   node scripts/smoke-phase6.mjs http://localhost:3200
 * It drives pitch → discovery → architecture → implementation plan → documentation ingestion → grounded answer → citation, and exits non-zero on the first failure.
 */
const BASE = process.argv[2] ?? 'http://localhost:3200';
let cookie = '';
async function call(method, path, body) {
  const res = await fetch(BASE + path, { method, headers: { ...(body !== undefined ? { 'content-type': 'application/json' } : {}), ...(cookie ? { cookie } : {}) }, body: body !== undefined ? JSON.stringify(body) : undefined });
  for (const c of res.headers.getSetCookie?.() ?? []) { const pair = c.split(';')[0]; if (pair.startsWith('p2p_session=')) cookie = pair; }
  const text = await res.text(); let json = {}; try { json = JSON.parse(text); } catch { /* sse */ }
  return { status: res.status, json, text };
}
const ok = async (m, p, b) => { const r = await call(m, p, b); if (r.status >= 400) throw new Error(`${m} ${p} → ${r.status} ${JSON.stringify(r.json.error ?? r.text.slice(0, 200))}`); return r.json.data; };
const until = async (fn, done, what, ms = 120_000) => { const end = Date.now() + ms; for (;;) { const v = await fn(); if (done(v)) return v; if (Date.now() > end) throw new Error(`timed out: ${what}`); await new Promise((r) => setTimeout(r, 700)); } };
const step = (m) => console.log(`✓ ${m}`);
const assert = (c, m) => { if (!c) throw new Error(`ASSERT FAILED: ${m}`); };

await ok('GET', '/api/health'); step('health');
await ok('POST', '/api/auth/dev-sign-in', { email: `smoke-${Date.now()}@example.com` });
const { project } = await ok('POST', '/api/projects', { name: 'Smoke' }); const id = project.id;
await ok('POST', `/api/projects/${id}/pitch`, { content: 'I want to create a platform that processes millions of transaction events in real time and detects fraud. Merchants should get alerts when a payment looks suspicious.' });
await ok('POST', `/api/projects/${id}/interpret`, {}); step('pitch interpreted');
let { state } = await ok('POST', `/api/projects/${id}/discovery/start`, {});
for (let i = 0; i < 2; i++) {
  const r = state.rounds.find((x) => x.status === 'OPEN');
  await ok('POST', `/api/projects/${id}/discovery/rounds/${r.id}/answers`, { answers: r.questions.map((q) => ({ questionId: q.id, choice: q.answerType === 'FREE_TEXT' ? { kind: 'FREE_TEXT', text: 'No preference' } : { kind: 'OPTIONS', optionIds: [q.options[0].id] } })) });
  ({ state } = await ok('POST', `/api/projects/${id}/discovery/next`, {}));
}
const { brief } = await ok('POST', `/api/projects/${id}/brief/generate`, {});
await ok('POST', `/api/projects/${id}/brief/confirm`, { briefVersionId: brief.version.id, acceptedUnknownIds: [] }); step('requirements confirmed');
await ok('POST', `/api/projects/${id}/architecture/generate`, {});
await until(() => ok('GET', `/api/projects/${id}/architecture`), (r) => r.architecture.state === 'READY', 'architecture (is the external worker running?)'); step('architecture generated by the external worker');
await ok('POST', `/api/projects/${id}/implementation/generate`, {});
const impl = await until(() => ok('GET', `/api/projects/${id}/implementation`), (r) => ['READY', 'FAILED'].includes(r.implementation.state), 'implementation plan');
assert(impl.implementation.state === 'READY', 'plan READY'); step('implementation plan generated');

const first = await ok('GET', `/api/projects/${id}/components/primary-database/docs`);
assert(['PREPARING', 'READY'].includes(first.docs.availability), `first docs availability ${first.docs.availability}`);
const docs = await until(() => ok('GET', `/api/projects/${id}/components/primary-database/docs`), (r) => r.docs.availability === 'READY' && r.docs.documents.length > 0, 'documentation ingestion by the worker');
assert(docs.docs.documents.every((d) => d.url.startsWith('https://')), 'https only'); step(`documentation ingested (${docs.docs.documents.length} documents)`);

const ask = async (message) => { const r = await call('POST', '/api/assistant/messages', { projectId: id, scope: 'COMPONENT', scopeId: 'primary-database', message, clientMessageId: `cm-${Math.random().toString(36).slice(2, 12)}` }); const blocks = r.text.split('\n\n').filter(Boolean).map((b) => JSON.parse(/^data: (.+)$/m.exec(b)[1])); const done = blocks.at(-1); assert(done.type === 'done', `answer completed: ${r.text.slice(-200)}`); return done.message.structured; };
const grounded = await ask('How do I require TLS for remote clients?');
assert(grounded.grounding.status === 'GROUNDED', `grounded, got ${grounded.grounding.status}`); assert(grounded.citations.length >= 1, 'has a citation'); step('grounded answer with citation');
const cite = await ok('GET', `/api/knowledge/citations/${grounded.citations[0].id}`); assert(cite.citation.url === grounded.citations[0].url, 'citation resolves'); step('citation snapshot readable');
const off = await ask('How do I tune autovacuum workers?');
assert(off.grounding.status !== 'GROUNDED' && off.citations.length === 0, 'off-topic answer is not grounded'); step(`off-topic answer is ${off.grounding.status}, no citations`);
console.log('SMOKE OK');
